services:
  db:
    container_name: 'postgres-db'
    image: postgres:alpine
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=appuser
      - POSTGRES_PASSWORD=pirate
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
